pizzas/urls.py
"""Определяет схемы URL для pizzas."""

from django.urls import path

from . import views

app_name = 'pizzas'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),

    # Вывод всех товаров.
    path('pizzas/', views.pizzas, name='pizzas' ),

    # Страница с подробной информацией по товару
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self):
        return self.name

pizzas/views.py
from django.shortcuts import render
from .models import Pizza

def index(request):
    """Домашняя страница приложения Pizzeria"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Выводит список пицц."""
    pizzas = Pizza.objects.all()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Выводит одну пиццу и всю по ней информацию."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

pizzas/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
  <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>
{% block content %}{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends 'pizzas/base.html' %}

{% block content %}
<p>Huge selection of two pizzes :)</p>
{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <p>Toppings:</p>
  <ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping.name|linebreaks }}</p>
    </li>
  {% empty %}
    <li>There are no toppings fo this pizza yet.</li>
  {% endfor %}
  </ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizzas</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>no this pizza.</li>
    {% endfor %}
  </ul>

{% endblock content %}